name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
          
      - name: Install Dependencies
        run: bun install
        
      - name: Build
        run: bun run build

      - name: Add headers
        run: |
          echo '/* /index.html 200' > dist/_redirects
          echo '/*.js application/javascript' > dist/_headers
          echo '/*.tsx application/javascript' >> dist/_headers
        
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
